



spring:
  profiles:
    active: @active@


#  security:
#    basic:
#      enabled: true
#    user:
#      name: user
#      password: 123
#spring:
#  application:
#    name: eureka
#
#server:
#  port: 8000
#
#eureka:
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://localhost:8000/eureka
